name: mpt-t2s-7b-nsql-v1

compute:
  cluster: r7z2
  gpus: 32  # Number of GPUs to use

  ## These configurations are optional
  # cluster: r0z0 # Name of the cluster to use for this run
  #gpu_type: h100_80gb # Type of GPU to use.
#metadata:
#  llm_foundry_dependency: 34d04ea689a4e4b08af7e9e911338fd4bc2983c1

integrations:
  # Clone and install the llm-foundry repo so we can run scripts from it
  - integration_type: git_repo
    git_repo: mosaicml/llm-foundry
    pip_install: -e .[gpu-flash2,databricks]
    ssh_clone: false # Should be true if using a private repo


# cd into the llm-foundry/scripts directory and run the train.py script
command: |
  cd llm-foundry/scripts
  python misc/download_hf_model.py --model mosaicml/mpt-7b-8k --token "${HUGGING_FACE_HUB_TOKEN}" --download-from cache --cache-url "https://${HOST_IP}:13579/models-hf/" --ignore-cert --fallback
  composer train/train.py $PARAMETERS

#image: "mosaicml/llm-foundry:2.0.1_cu118-latest"
image: mosaicml/llm-foundry:2.1.0_cu121_flash2-latest

# The parameters section is mounted to /mnt/config/parameters.yaml in the container
# The mounted file is then passed directly to the train.py script
# See LLM-foundry llmfoundry/scripts/train.py to see how the parameters are used in code
parameters:
  #autoresume: true
  # Path to load the weights from the previous step

  # Where to read the data from and save it to locally on the machine
  data_path: s3://msh-tmp1/t2s/nsql_dolly_prompt_v1_072_limit50000/
  data_local: ./local-dataset-composercodebase-cache/

  # Checkpoint to local filesystem or remote object store
  save_interval: 1ep # How frequently to save checkpoints
  save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
  save_folder: s3://msh-tmp1/t2s/checkpoints/mpt-1b-nsql-20k-v1-test1/
  overwrite: true
  #save_weights_only: true # Since we only need the weights for the next step, we can reduce the size of the checkpoint

  # Maximum sequence length of the model
  # For MPT, you can change this to a different number if you would like to train on longer sequences
  # Note that you would also need to reprocess your data to contain longer sequences
  max_seq_len: 8192

  # Random seed to ensure reproducibility
  global_seed: 15

  # Run Name
  run_name: # If left blank, will be read from env var $RUN_NAME

  model:
    name: hf_causal_lm
    pretrained: true
    init_device: mixed # Initially only create the model on CPU once per node to reduce system memory requirements
    pretrained_model_name_or_path: mosaicml/mpt-7b-8k-instruct
    config_overrides: # Override the default model config (comment this out if you change the model from MPT)
      attn_config:
        attn_impl: triton # Use the triton implementation of attention
        attn_uses_sequence_id: false

  # Tokenizer
  # This section is used by LLM-foundry to construct the tokenizer
  tokenizer:
    name: mosaicml/mpt-7b
    kwargs:
      model_max_length: ${max_seq_len}

  # Dataloaders
  train_loader:
    name: finetuning
    dataset:
      remote: ${data_path}
      local: ${data_local}
      split: train
      shuffle: true
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
      #shuffle_algo: py1e
      #packing_ratio: auto
      allow_pad_trimming: false
      decoder_only_format: true
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  eval_loader:
    name: finetuning
    dataset:
      remote: ${data_path}
      local: ${data_local}
      split: val
      shuffle: false
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
      #shuffle_algo: py1e
      allow_pad_trimming: false
      decoder_only_format: true
      #packing_ratio: auto
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  # Learning rate scheduler
  # see LLM-foundry llmfoundry/utils/builders.py::build_scheduler for other built-in options
  scheduler:
    name: linear_decay_with_warmup
    t_warmup: 0.02dur
    alpha_f: 0.1

  # Optimizer
  # see LLM-foundry llmfoundry/utils/builders.py::build_optimizer for other built-in options
  optimizer:
    name: decoupled_lionw
    lr: 0.0000001
    betas:
      - 0.9
      - 0.95
    weight_decay: 0

  # Algorithms to apply
  # see https://docs.mosaicml.com/projects/composer/en/latest/trainer/algorithms.html
  # for an explanation of algorithms in Composer
  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  # Run configuration
  max_duration: 10ba # Maximum duration of the run. Change to something shorter (e.g. 10ba) for a quick test run
  eval_interval: 10ba # How frequently to evaluate the model
  eval_first: false # Whether to evaluate the model before training
  #eval_subset_num_batches: -1 # How many batches to evaluate on. -1 means evaluate on the entire dataset
  global_train_batch_size: 64  # Global batch size. This is the batch size across all GPUs and should be 8*num_gpus
  seed: ${global_seed}
  device_eval_batch_size: 8 # Evaluation batch size per GPU
  device_train_microbatch_size: 8 #
  precision: amp_bf16

  # Configuration settings for FSDP
  # https://docs.mosaicml.com/projects/composer/en/latest/notes/distributed_training.html#fullyshardeddataparallel-fsdp
  # for more information about FSDP in Composer
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: true
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false

  # Logging configuration
  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba
  python_log_level: debug

  # Uncomment to log to WandB
  # see LLM-foundry llmfoundry/utils/builders.py::build_logger for other built-in options
  loggers:
    mlflow:
      experiment_name: /Shared/msh_test_exp
      model_registry_prefix: msh.t2s
      model_registry_uri: databricks-uc
      tracking_uri: databricks

  # Callbacks
  # see LLM-foundry llmfoundry/utils/builders.py::build_callbacks for other built-in options
  callbacks:
    hf_checkpointer:
      # Save a Hugging Face formatted checkpoint at the end of each epoch
      save_interval: 1ep
      # The Hugging Face formatted checkpoints will be saved inside a subfolder called huggingface,
      # so this folder will likely be the same as your overall save_folder
      save_folder: s3://msh-tmp1/t2s/checkpoints/mpt-7b-nsql-5k-hf-v1/
      # Set the precision you want the checkpoint saved in
      precision: bfloat16

    # Periodically generate text from the model, uncomment only if you are logging to WandB
    # generate_callback:
    #   batch_log_interval: 500
    #   do_sample: true
    #   max_new_tokens: 100
    #   prompts:
    #   - The quick brown fox jumps over
    #   - |-
    #     Vegan Banana Bread
    #     Instructions:
    #     1.
    #   - The other day I was explaining what generative AI is to my five year old.
    #   - We are a global semiconductor company primarily offering
    #   - Our company had revenue of
    #   - Our business operations are subject to numerous risks, including
    #   temperature: 1
    #   top_k: 50
    #   top_p: 0.95
    #   use_cache: true
    # Log information about the processing speed of the model
    speed_monitor:
      window_size: 10
    # Log the learning rate over the course of training
    lr_monitor: {}
    # Log information about the memory usage of the model
    memory_monitor: {}
    # Log an estimate of how long the training run has left to complete
    runtime_estimator: {}

